# Generated by Django 4.0 on 2022-01-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone_Number',
            field=models.IntegerField(null=True),
        ),
    ]
