# Generated by Django 4.0 on 2022-03-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
