# Generated by Django 4.0 on 2022-02-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_aboutus_description_alter_services_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
