# Generated by Django 4.0 on 2022-03-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_portfolio_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='about'),
        ),
    ]
