# Generated by Django 4.0 on 2022-01-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_contactus_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone_Number',
            field=models.CharField(max_length=20),
        ),
    ]
