# Generated by Django 4.0 on 2022-03-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_services_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdata',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
