# Generated by Django 4.0 on 2022-01-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_contactus_contactnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='contactNumber',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
