# Generated by Django 4.0 on 2022-01-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_contactus_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone_Number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
