# Generated by Django 4.0 on 2022-02-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_clientdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dynamicslider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dynamic_slider_images')),
            ],
        ),
    ]
