# Generated by Django 4.0 on 2022-01-24 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_contactus_contactnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='contactNumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
