# Generated by Django 4.0 on 2022-01-24 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_contactus_contactnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='contactNumber',
        ),
        migrations.AddField(
            model_name='contactus',
            name='phoneNumber',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
