# Generated by Django 4.0 on 2022-02-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_dynamicslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicslider',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
