# Generated by Django 4.0 on 2022-01-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_contactus_contactnumber_contactus_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='phoneNumber',
            new_name='phone_Number',
        ),
    ]
