# Generated by Django 4.0 on 2022-02-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_dynamicslider_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='heading',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
