# Generated by Django 4.0 on 2022-03-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_aboutus_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='servicesDeatils'),
        ),
    ]
