# Generated by Django 4.0 on 2022-03-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team')),
            ],
        ),
    ]
