# Generated by Django 4.0 on 2022-03-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='qualification',
            field=models.CharField(default=1, max_length=350),
            preserve_default=False,
        ),
    ]
