# Generated by Django 4.0 on 2022-03-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_services_contactus_date_created_and_more'),
        ('blog', '0007_services'),
        ('blog', '0009_rename_phonenumber_contactus_phone_number'),
        ('blog', '0017_team_qualification'),
    ]

    operations = [
    ]
